Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,26 +1,48 @@
 #!/bin/sh
 
+set -e  # Exit immediately if a command fails
+
 indent() {
   sed -u 's/^/       /'
 }
 
 echo "-----> Install bento4"
-BUILD_DIR="$1"
-VENDOR_DIR="vendor"
-GITHUB_URL="https://github.com/DigitalSapphire/heroku-buildpack-bento4-latest.git"
+BUILD_DIR=$1
+VENDOR_DIR="${BUILD_DIR}/vendor"
+WEBPAGE_URL="https://www.bento4.com/downloads/"
+DOWNLOAD_URL=$(curl -L $WEBPAGE_URL | grep -o "http:\/\/.*linux\.zip")
 
-echo "Using buildpack from GitHub URL: $GITHUB_URL" | indent
+echo "DOWNLOAD_URL = ${DOWNLOAD_URL}" | indent
 
-cd "$BUILD_DIR"
-mkdir -p "$VENDOR_DIR"
-cd "$VENDOR_DIR"
-git clone --quiet "$GITHUB_URL" bento4
+# Check if curl and unzip are installed
+command -v curl >/dev/null 2>&1 || { echo >&2 "curl is required but it's not installed. Aborting."; exit 1; }
+command -v unzip >/dev/null 2>&1 || { echo >&2 "unzip is required but it's not installed. Aborting."; exit 1; }
 
+# Create a temporary directory for downloads
+TMP_DIR=$(mktemp -d)
+cd ${TMP_DIR}
+
+# Download and extract Bento4
+curl -L --silent ${DOWNLOAD_URL} -o bento4.zip
+unzip -qq bento4.zip
+mv Bento4* bento
+
+# Remove existing Bento4 directory if present
+if [ -d "${VENDOR_DIR}/bento4" ]; then
+    echo "Removing existing Bento4 installation"
+    rm -rf "${VENDOR_DIR}/bento4"
+fi
+
+# Move the downloaded Bento4 to the vendor directory
+mv bento/bin "${VENDOR_DIR}/bento4"
+
+# Export PATH
 echo "exporting PATH" | indent
-PROFILE_PATH="$BUILD_DIR/.profile.d/bento4.sh"
-mkdir -p "$(dirname "$PROFILE_PATH")"
-echo 'export PATH="$PATH:${HOME}/vendor/bento4"' > "$PROFILE_PATH"
+PROFILE_PATH="${BUILD_DIR}/.profile.d/bento4.sh"
+mkdir -p "$(dirname $PROFILE_PATH)"
+echo 'export PATH="$PATH:${HOME}/vendor/bento4"' > $PROFILE_PATH
 
+# Clean up
 echo "-----> Cleaning Up"
 echo "removing extra files" | indent
-rm -rf bento
+rm -rf ${TMP_DIR}
